version: '3.8'
services:
  devcontainer:
    build: 
      context: .
      dockerfile: Dockerfile
    init: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ..:/workspace:cached
      - ~/.config/gh/hosts.yml:/root/.config/gh/hosts.yml
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    network_mode: service:qdrant
    depends_on:
      - qdrant
  qdrant:
    image: qdrant/qdrant
    ports:
      - 6333:6333
  redis:
    image: redis:alpine
    network_mode: service:qdrant
  zipkin:
    image: openzipkin/zipkin-slim:latest
    ports:
      - 9411:9411
  dapr-placement:
    image: "daprio/dapr"
    command: ["./placement", "--port", "50005"]
    network_mode: service:qdrant